---
number: 0
course: Computer Science 1
material: Rules
---

# Rules of the subject Computer Science I

1. This class is divided into lectures and obligatory laboratory classes.
2. Grading is done using a $0$ to $100$ point scale:
    a. $60$ points for $2$ lecture tests worth $30$ points each,
    b. $40$ points for laboratories ($2$ tests worth $20$ points each).
3. A passing mark is given only, if a student obtained a minimum number of points, i.e.:
    a. 21 points from the laboratories,
    b. 31 points from both lecture tests
Failing to achieve the minimum number of points results in a failing grade (2).
4. In case a minimum requirements, outlined in point 3, are passed, the final grade is
calculated as follows:
    a. 0-50: 2.0
    b. 51-60: 3.0
    c. 61-70: 3.5
    d. 71-80: 4.0
    e. 81-90: 4.5
    f. 91-100: 5.0
5. A dead line for collecting points is the last day of the semester.
After the last day of the semester the grade becomes final.
There will be no corrections.
6. Laboratory attendance is obligatory.
Each absence needs to be excused, e.g. with a medical leave.
Failing to do so results in deduction of $3$ points.
7. Laboratory groups are formed based on the dean's office list enumeration.
    a. 1-12 room 120
    b. 13-24 room A3
    c. 25 and higher will be assigned to the additional group.
8. During the last lecture there will be an additional, correction test worth $50$ points.
    a. If better, the mark of the correction test replaces results of both lecture tests.
    b. To be eligible for the correction test:
        i. At least one of the lecture tests must be passed with more than $50%$ (16 points).
        ii. Student must be present at at least 8 lectures.
