name: Publish to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt install -y build-essential pandoc libxml2-dev libssl-dev libcurl4-openssl-dev r-base r-base-dev r-cran-devtools;
          sudo apt install -y libharfbuzz-dev libfribidi-dev;
          sudo R -e "devtools::install_github('rstudio/rmarkdown')";
          wget https://github.com/mathjax/MathJax/archive/master.zip;
          unzip master.zip >/dev/null;
          rm master.zip;
          export RMARKDOWN_MATHJAX_PATH=$PWD/MathJax-master;

      - name: Build site
        run: |
          R -e "rmarkdown::render_site()";
          tools/headers;
      - name: Upload site artifact for review
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4.6.1
        with:
          name: site_for_review
          path: _site
      - name: Publish
        if: ${{ github.event_name == 'push' }}
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          build_dir: _site
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
