name: Publish to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup tinytex
        uses: r-lib/actions/setup-tinytex@v2
      - name: Setup dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      - name: Build site
        run: R -e "rmarkdown::render_site()";
      - name: Correcting headers
        run: tools/headers;
      - name: Upload site artifact for review
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4.6.1
        with:
          name: site_for_review
          path: _site
      - name: Publish
        if: ${{ github.event_name == 'push' }}
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          build_dir: _site
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
